server.port=8083

# 1. Simplify the name (The old name was too long and prone to typos)
spring.application.name=microservice1

# 2. CRITICAL FIX: Force Eureka to use IP Address instead of Hostname
eureka.instance.prefer-ip-address=true

# Discovery Server Access
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=centennial

spring.main.web-application-type=reactive
logging.level.org.springframework=ERROR
logging.level.com=TRACE
eureka.instance.status-page-url-path=/